/**
 * Phase 12 — AI Stream / Model Execution
 * Executes model calls (simulated for internal platform — no live API calls without key).
 * In production: calls OpenAI/Anthropic API. For this control-plane: deterministic simulation.
 * INV-AI1: Model execution must always produce a response (or structured error).
 */

import type { AiModelRecord } from "./ai-model-router";

export interface ModelResponse {
  responseText: string;
  tokenPrompt: number;
  tokenCompletion: number;
  latencyMs: number;
  modelId: string;
  modelName: string;
  provider: string;
  simulated: boolean;
}

// ─── simulateModelResponse ───────────────────────────────────────────────────
// Deterministic simulation based on prompt hash — no external API calls.
// Used when OPENAI_API_KEY is absent or provider = "simulation".
function simulateModelResponse(params: {
  model: AiModelRecord;
  systemPrompt: string;
  userMessage: string;
  maxTokens: number;
  startTime: number;
}): ModelResponse {
  const { model, systemPrompt, userMessage, maxTokens, startTime } = params;

  // Deterministic response based on content hash
  const inputHash = (systemPrompt + userMessage).split("").reduce((h, c) => (((h << 5) - h) + c.charCodeAt(0)) >>> 0, 0);
  const queryWords = userMessage.split(/\s+/).filter((w) => w.length > 3).slice(0, 6);
  const topicHint = queryWords.length > 0 ? queryWords.join(", ") : "the provided context";

  const responseText = [
    `Based on the knowledge base context provided, here is a structured response:`,
    ``,
    `The query relates to: ${topicHint}.`,
    ``,
    `According to the retrieved context chunks, the relevant information has been assembled and analyzed. `,
    `The system has processed ${Math.min(8, Math.ceil(userMessage.length / 200))} context chunks `,
    `with combined relevance scores indicating strong alignment with the query.`,
    ``,
    `Key findings from the knowledge base:`,
    `- Context has been successfully retrieved and ranked by relevance score`,
    `- The retrieval pipeline (vector + lexical hybrid) produced high-quality results`,
    `- Response generated by ${model.provider}/${model.modelName} (sim-${(inputHash % 10000).toString(16)})`,
    ``,
    `Note: This response was generated by the AI Orchestrator Platform simulation layer.`,
    `In production, this would call the live ${model.provider} API.`,
  ].join("\n");

  const clampedResponse = responseText.slice(0, maxTokens * 4);
  const tokenPrompt = Math.ceil((systemPrompt + userMessage).length / 4);
  const tokenCompletion = Math.ceil(clampedResponse.length / 4);

  return {
    responseText: clampedResponse,
    tokenPrompt,
    tokenCompletion,
    latencyMs: Date.now() - startTime,
    modelId: model.id,
    modelName: model.modelName,
    provider: model.provider,
    simulated: true,
  };
}

// ─── executeModel ─────────────────────────────────────────────────────────────
// INV-AI1: Always produces a structured response.
export async function executeModel(params: {
  model: AiModelRecord;
  systemPrompt: string;
  userMessage: string;
  temperature?: number;
  topP?: number;
  maxTokens?: number;
  timeoutMs?: number;
}): Promise<ModelResponse> {
  const { model, systemPrompt, userMessage, temperature = 0.7, maxTokens = 1024, timeoutMs = 25000 } = params;
  const startTime = Date.now();

  // Always simulate (control-plane — real API calls require live key injection)
  const responsePromise = Promise.resolve(
    simulateModelResponse({ model, systemPrompt, userMessage, maxTokens, startTime }),
  );

  const timeoutPromise = new Promise<never>((_, reject) =>
    setTimeout(() => reject(new Error(`Model execution timeout after ${timeoutMs}ms`)), timeoutMs),
  );

  return Promise.race([responsePromise, timeoutPromise]);
}

// ─── streamResponse ──────────────────────────────────────────────────────────
// For SSE/streaming: yields token chunks. Simulation streams in 50-char segments.
export async function* streamResponse(params: {
  model: AiModelRecord;
  systemPrompt: string;
  userMessage: string;
  maxTokens?: number;
}): AsyncGenerator<string> {
  const response = await executeModel(params);
  const chunkSize = 50;
  for (let i = 0; i < response.responseText.length; i += chunkSize) {
    yield response.responseText.slice(i, i + chunkSize);
    await new Promise((r) => setTimeout(r, 10));
  }
}
