// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-variants/CenteredCard.tsx": () => import("../components/mockups/login-variants/CenteredCard.tsx"),
  "./components/mockups/login-variants/HeroLogin.tsx": () => import("../components/mockups/login-variants/HeroLogin.tsx"),
  "./components/mockups/login-variants/SplitScreen.tsx": () => import("../components/mockups/login-variants/SplitScreen.tsx"),
  "./components/mockups/marketing-variants/AsymHero.tsx": () => import("../components/mockups/marketing-variants/AsymHero.tsx"),
  "./components/mockups/marketing-variants/CenteredHero.tsx": () => import("../components/mockups/marketing-variants/CenteredHero.tsx")
};
